---
- hosts: appservers
  tasks:
  - name: installing git
    yum:
       name: git 
       state: present 
  - name: installing maven
    yum: 
       name: maven
       state: present
  - name: copying pem file 
    copy:
        src: /home/ec2-user/mamu1031.pem
        dest: /root/ansible1     
  - name: installing httpd
    yum:
       name: httpd
       state: present
  - name: restart httpd
    service: 
          name: httpd 
          state: restarted     